Dialyzer
DrPandemic/MasDB pull request #38
Opened 2017-04-15 19:39 UTC by DrPandemic

This is a proposal, feel free to reject it.

In my next PR, I would like to use `@spec`. At the same time, I though that adding dialyzer would be a great idea to validate the spec. But, dialyzer had a hard time validating our usage of the pipe module. I replaced them by `with`. I think it's a little by more code for the caller, but it's more clear. Also, it let the callee have any signature.

If you want to run dializer, you can simply `mix dialyzer`.

What's your opinion on that?

2017-04-16 17:56 UTC, samdus requested changes
It would be interesting to remove the :ok flag from the triplet.

2017-04-17 00:59 UTC, DrPandemic commented
Could we pass this one? I'll do another PR for that

2017-04-17 13:54 UTC, samdus approved these changes

2017-04-17 20:43 UTC, merged

2017-04-17 21:28 UTC, DrPandemic commented
After trying to remove the `:ok` I found that it was useful. If we remove it, we would have no way of knowing if the transformation worked.